// Mocks generated by Mockito 5.4.6 from annotations
// in omniconnect_fitness/test/services/notification_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:omniconnect_fitness/services/api_client.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i3.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i2.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> clearToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearToken, []),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<T> get<T>(
    String? endpoint, {
    Map<String, dynamic>? queryParameters,
    required T Function(dynamic)? fromJson,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [endpoint],
              {#queryParameters: queryParameters, #fromJson: fromJson},
            ),
            returnValue:
                _i4.ifNotNull(
                  _i4.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #get,
                      [endpoint],
                      {#queryParameters: queryParameters, #fromJson: fromJson},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #get,
                    [endpoint],
                    {#queryParameters: queryParameters, #fromJson: fromJson},
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> post<T>(
    String? endpoint, {
    required dynamic body,
    required T Function(dynamic)? fromJson,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [endpoint],
              {#body: body, #fromJson: fromJson},
            ),
            returnValue:
                _i4.ifNotNull(
                  _i4.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #post,
                      [endpoint],
                      {#body: body, #fromJson: fromJson},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #post,
                    [endpoint],
                    {#body: body, #fromJson: fromJson},
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> put<T>(
    String? endpoint, {
    required dynamic body,
    required T Function(dynamic)? fromJson,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [endpoint],
              {#body: body, #fromJson: fromJson},
            ),
            returnValue:
                _i4.ifNotNull(
                  _i4.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #put,
                      [endpoint],
                      {#body: body, #fromJson: fromJson},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #put,
                    [endpoint],
                    {#body: body, #fromJson: fromJson},
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> patch<T>(
    String? endpoint, {
    required dynamic body,
    required T Function(dynamic)? fromJson,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [endpoint],
              {#body: body, #fromJson: fromJson},
            ),
            returnValue:
                _i4.ifNotNull(
                  _i4.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #patch,
                      [endpoint],
                      {#body: body, #fromJson: fromJson},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #patch,
                    [endpoint],
                    {#body: body, #fromJson: fromJson},
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> delete<T>(
    String? endpoint, {
    required T Function(dynamic)? fromJson,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [endpoint], {#fromJson: fromJson}),
            returnValue:
                _i4.ifNotNull(
                  _i4.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #delete,
                      [endpoint],
                      {#fromJson: fromJson},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#delete, [endpoint], {#fromJson: fromJson}),
                ),
          )
          as _i2.Future<T>);
}
